### ISSUE TITLE
check codecov after Travis was disabled

### ISSUE THREAD

**Issue by vladak** [vladak/photo-backup#18]
It seems that codecov reports depend on Travis builds. This will probably break after today's removal of Travis configuration.

**Comment by vladak** [comment]
There is now [codecov Github Action](https://github.com/marketplace/actions/codecov) that works without having to deal with Codecov token.

The action needs to run the tests, then convert the coverage file to XML and then invoke the action:
```yml
      - run: pytest --cov=./                                                    
      - run: coverage xml                                                       
      - uses: codecov/codecov-action@v2
```
